jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud